### ISSUE TITLE
Mod fails to load on v0.18.2

### ISSUE THREAD

**Issue by RkShaRkz** [Klonan/Teleporters#1]
Error message:

Error loading mods
Failed to load mods: Error while loading item prototype "teleporter"(item):Sprite '__Teleporters__/data/entities/teleporters/teleporter-icon.png' has mipmap count set to 4, so it's size is expected to be multiple of 8. But it's size is 97x97.

Looks like you'll have to fix the image. I'll send you a PR if i get to it first.

**Comment by RkShaRkz** [comment]
Fixed by #3

**Comment by Klonan** [comment]
Its fixed
